sudo: required
language: node_js
node_js:
- '8'
before_install:
- gem install sass
- gem install scss_lint
- npm install -g npm
- npm install promise
before_script:
- npm install -g gulp
script:
- gulp deploy
- npm test
- gulp coveralls
